#!/usr/bin/python
#+
# This script acts as a relay between two TCP endpoints, logging
# everything that goes over the connection. Invoke it as follows:
#
#     middleman --relay=localport:remoteaddr:remoteport
#
# Created by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>.
#-

import sys
import select
import socket
import getopt
import random

#+
# Connection management
#-

relay = {} # indexed by local port, values are dictionaries
  # keys in each value dictionary:
  #     listen -- socket to listen on for local connection attempts
  #     remotehost -- remote host name/address to connect to (informational)
  #     remoteport -- remote port to connect to (informational)
  #     addrinfo -- expanded list of alternative remote protocol addresses to connect to
  #     inet6 -- True if connections use IPv6, False for IPv4
  #     connected -- list of opened connections to this host/port
  #
  # Each entry in relay[port]["connected"] is a dictionary with keys as follows:
  #     local -- context for local connection
  #     remote -- context for remote connection
  # Each context object is a dictionary with keys as follows:
  #     socket -- connection socket
  #     buf -- data awaiting writing to socket
  #     eof -- whether EOF has been received
  #     writeend -- whether EOF has been sent (not needed?)

maxbuf = 4096 # how much data to buffer at a time

directions = (("local", "remote"), ("remote", "local"))

#+
# Mainline
#-

(opts, args) = getopt.getopt \
  (
	sys.argv[1:],
	"",
	["external", "relay="]
  )
if len(args) != 0 :
	raise getopt.GetoptError("no arguments expected")
#end if
loopback_only = True
for keyword, value in opts :
	if keyword == "--external" :
		loopback_only = False
	elif keyword == "--relay" :
		if hasattr(value, "partition") :
			# allow for embedded colons in an IPv6 address
			value = value.partition(":")
			items = () # in case of parse failure
			if value[1] == ":" :
				value = (value[0],) + value[2].rpartition(":")
				if value[2] == ":" :
					items = (value[0], value[1].lstrip("[").rstrip("]"), value[3])
				#end if
			#end if
		else :
			items = value.split(":")
		#end if
		if len(items) != 3 :
			raise getopt.GetoptError("usage: --relay=localport:remoteaddr:remoteport")
		#end if
		localport = int(items[0])
		remoteport = int(items[2])
		if relay.has_key(localport) :
			raise getopt.GetoptError("duplicate entry for local port %d" % localport)
		#end if
		relay[localport] = \
			{
				"remotehost" : items[1],
				"remoteport" : remoteport,
				"addrinfo" :
					[
						i for i in socket.getaddrinfo(items[1], remoteport)
							if i[1] == socket.SOCK_STREAM
					],
				"listen" : None,
				"connected" : [],
			}
		relay[localport]["inet6"] = relay[localport]["addrinfo"][0][0] == socket.AF_INET6
		  # assuming I won't get a mixture of v4 and v6!
	#end if
#end for
if len(relay) == 0 :
	raise getopt.GetoptError("no --relay items specified")
#end if

for localport, item in relay.items() :
	# open listeners on all local sockets
	item["listen"] = socket.socket \
	  (
		(socket.AF_INET, socket.AF_INET6)[item["inet6"]],
		socket.SOCK_STREAM
	  )
	item["listen"].bind \
	  (
		(
			(("0.0.0.0", "127.0.0.1")[loopback_only], ("::", "::1")[loopback_only])[item["inet6"]],
			localport,
		)
	  )
	item["listen"].listen(socket.SOMAXCONN)
#end for
try :
	while True :
		# run listeners and data transfers
		readable = []
		writable = []
		trouble = []
		for item in relay.values() :
			readable.append(item["listen"])
			trouble.append(item["listen"])
			for connection in item["connected"] :
				for (this, other) in directions :
					if not connection[this]["eof"] and len(connection[other]["buf"]) < maxbuf :
						readable.append(connection[this]["socket"])
					#end if
					if len(connection[this]["buf"]) != 0 :
						writable.append(connection[this]["socket"])
					#end if
					trouble.append(connection[this]["socket"])
				#end for
			#end for
		#end for
		(readable, writable, trouble) = select.select(readable, writable, trouble)
		readable = set(readable)
		writable = set(writable)
		trouble = set(trouble)
		# NYI check for trouble
		for localport, item in relay.items() :
		  # give highest priority to writes
			new_connected = []
			for connection in item["connected"] :
				connection_ok = True # initial assumption
				for (this, other) in directions :
					if connection[this]["socket"] in writable :
						try :
							nrbytes = connection[this]["socket"].send(connection[this]["buf"])
						except socket.error, (ErrNo, Msg) :
							sys.stderr.write \
							  (
									"%05d!error %d -- %s writing to %s\n"
								%
									(localport, ErrNo, Msg, this)
							  )
							nrbytes = None
						#end try
						if nrbytes != None :
							connection[this]["buf"] = connection[this]["buf"][nrbytes:]
							if len(connection[this]["buf"]) == 0 and connection[other]["eof"] :
								connection[this]["socket"].shutdown(socket.SHUT_WR)
								  # forward delayed EOF to this end
								connection[this]["writeend"] = True
							#end if
						else :
							connection_ok = False
						#end if
					#end if
				#end for
				if connection_ok :
					new_connected.append(connection)
				else :
					connection["local"]["socket"].close()
					connection["remote"]["socket"].close()
				#end if
			#end for
			item["connected"] = new_connected
		#end for
		for localport, item in relay.items() :
		  # give next priority to reads
			new_connected = []
			for connection in item["connected"] :
				connection_ok = True # initial assumption
				for (this, other) in directions :
					if connection[this]["socket"] in readable :
						try :
							data = connection[this]["socket"].recv \
							  (
								maxbuf - len(connection[other]["buf"])
							  )
						except socket.error, (ErrNo, Msg) :
							sys.stderr.write \
							  (
									"%05d!error %d -- %s reading from %s\n"
								%
									(localport, ErrNo, Msg, this)
							  )
							data = None
						#end try
						if data != None :
							if len(data) != 0 :
								continued = \
									(
										len(connection[other]["buf"]) != 0
									and
										connection[other]["buf"][-1] != "\n"
									)
								connection[other]["buf"] += data
								while True :
									pos = data.find("\n")
									if pos < 0 :
										pos = len(data) # all remaining data
									else :
										pos += 1 # include newline
									#end if
									line = data[:pos]
									data = data[pos:]
									if not continued :
										sys.stdout.write \
										  (
											"%05d%s" % (localport, ("<", ">")[this == "local"])
										  )
									#end if
									sys.stdout.write(line)
									continued = False
									if len(data) == 0 :
										break
								#end while
							else :
								if continued :
									sys.stdout.write("\n")
								#end if
								sys.stdout.write("%05d:%s EOF\n" % (localport, this))
								if len(connection[other]["buf"]) == 0 :
									connection[other]["socket"].shutdown(socket.SHUT_WR)
									  # forward EOF to other end
									connection[other]["writeend"] = True
								# else wait until buf is emptied before forwarding EOF
								#end if
								connection[this]["eof"] = True
							#end if
						else :
							connection_ok = False
						#end if
					#end if
				#end for
				if (
						connection_ok
					and
						not
							(
								connection["local"]["eof"]
							and
								connection["remote"]["eof"]
							and
								len(connection["local"]["buf"]) == 0
							and
								len(connection["remote"]["buf"]) == 0
							)
				) :
					new_connected.append(connection)
				else :
					# EOF sent and received in both directions, nothing further to do
					connection["local"]["socket"].close()
					connection["remote"]["socket"].close()
				#end if
			#end for
			item["connected"] = new_connected
		#end for
		for localport, item in relay.items() :
		  # give lowest priority to accepting new connections
			if item["listen"] in readable :
				(local, addr) = item["listen"].accept()
				sys.stderr.write \
				  (
					"%05d:connect from %s\n" % (localport, addr)
				  )
				remote = socket.socket \
				  (
					(socket.AF_INET, socket.AF_INET6)[item["inet6"]],
					socket.SOCK_STREAM
				  )
				connection = \
					{
						"local" :
							{
								"socket" : local,
								"buf" : "",
								"eof" : False,
								"writeend" : False,
							},
						"remote" :
							{
								"socket" : remote,
								"buf" : "",
								"eof" : False,
								"writeend" : False,
							},
					}
				addrinfo_totry = list(item["addrinfo"])
				random.shuffle(addrinfo_totry)
				addrinfo_totry = iter(addrinfo_totry)
				while True :
					try :
						addrinfo = addrinfo_totry.next()
					except StopIteration :
						raise RuntimeError \
						  (
							"can't open %s:%d" % (item["remotehost"], item["remoteport"])
						  )
					#end try
					try :
						remote.connect(addrinfo[4])
						break
					except socket.error, (ErrNo, Msg) :
						sys.stderr.write \
						  (
								"%05d!error %d -- %s connecting to %s\n"
							%
								(localport, ErrNo, Msg, repr(addrinfo))
						  )
					#end try
				#end while
				item["connected"].append(connection)
			#end if
		#end for
	#end while
except KeyboardInterrupt :
	pass
#end try
for item in relay.values() :
	# shut everything down
	for connection in item["connected"] :
		connection["local"]["socket"].close()
		connection["remote"]["socket"].close()
	#end for
	if item["listen"] !=  None :
		item["listen"].close()
	#end if
#end for
